### ISSUE TITLE
starts_with("spotify:ad:") causes an ad not to be detected

### ISSUE THREAD

**Issue by albarozzz** [KivalM/spotblock-rs#6]
`playerctl --player=spotify metadata --format '{{mpris:trackid}}'` reports:
a string starting with '/com/spotify/ad/' which makes the condition false because that is not 'spotify:ad:'

**Comment by KivalM** [comment]
Hey, thanks for pointing this out.

I did a bit of testing, the latest Spotify update changed the 'trackid' format.
Your PR seems to fix the problem, but only for users on the latest version of the Spotify client.

Some adjustments need to be made before I can merge it... 

Thank you
